services:
  mydb:
    image: stackupiss/northwind-db:v1
    environment:
      - DB_USER=root
      - DB_PASSWORD=changeit
    networks:
      - mynet
    volumes:
      - myvol:/var/lib/mysql
      
  myapp:
    image: stackupiss/northwind-app:v1
    networks:
      - mynet
    depends_on:
      - mydb
    environment:
      - DB_HOST=mydb
      - DB_USER=root
      - DB_PASSWORD=changeit
    ports:
      - 8080:3000

volumes:
  myvol:

networks:
  mynet:
    driver: bridge