
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb-deploy
  namespace: bggns
  labels:
    app: db
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydb-deploy
  template:
    metadata:
      labels:
        app: mydb-deploy
    spec:
      containers:
      - name: mydb-deploy
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mydb-svc
  namespace: bggns
  labels:
    env: prod
spec:
  selector:
    app: mydb-deploy
  ports:
  - name: db-port
    port: 3306
    targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggns-backend
  namespace: bggns  
  labels:
    app: backend
    env: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend 
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: bggns-backend
          image: stackupiss/bgg-backend:v1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000 
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000 
          envFrom:
          - configMapRef:
              name: bgg-cm
          - secretRef:
              name: bgg-secret

---
apiVersion: v1
kind: Service
metadata:
  name: bggns-backend
  namespace: bggns
  labels:
    app: backend
    env: prod
spec:
  selector:
    app: backend
  ports:
  - name: backend-port
    port: 8080
    targetPort: 3000